# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_fwcAdDzmaerKjrWNMMWhL4mxDCZfZu
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile # Import the zipfile module
import os # Import the os module

# Enable inline plots
# %matplotlib inline

zip_path = "/content/covid 19.zip"
csv_file_name = "Covid19 India (Jan 20 - Mar 20).csv"
extracted_path = "/content/" + csv_file_name


with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extract(csv_file_name, "/content/")

df = pd.read_csv(extracted_path)

print("First 5 rows of the dataset:")
print(df.head())

print(df.info())

print(df.isnull().sum())

plt.figure(figsize=(12, 6))

df["ConfirmedIndianNational"] = df["ConfirmedIndianNational"].fillna(0)
df["ConfirmedForeignNational"] = df["ConfirmedForeignNational"].fillna(0)
df["Confirmed"] = df["ConfirmedIndianNational"] + df["ConfirmedForeignNational"]

#Fill missing values
df["Cured"] = df["Cured"].fillna(0)
df["Deaths"] = df["Deaths"].fillna(0)

plt.figure(figsize=(12, 6))
df.groupby("State/UnionTerritory")["Confirmed"].sum().sort_values(ascending=False).plot(kind='bar', color='orange')

plt.title("Total Confirmed COVID-19 Cases by State/UnionTerritory")
plt.xlabel("State")
plt.ylabel("Total Confirmed Cases")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

total_deaths = df["Deaths"].sum()
total_cured = df["Cured"].sum()

plt.figure(figsize=(6, 6))
plt.pie([total_deaths, total_cured],
        labels=["Deaths", "Cured"],
        autopct="%1.1f%%",
        colors=["red", "green"],
        startangle=90)
plt.title("Overall Deaths vs Cured in India")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(df[["Confirmed", "Cured", "Deaths"]].corr(), annot=True, cmap="coolwarm")
plt.title("Correlation between Confirmed, Cured, and Deaths")
plt.show()

# Time-Series Trend (if Date is usable)
df["Date"] = pd.to_datetime(df["Date"])
daily_summary = df.groupby("Date")[["Confirmed", "Cured", "Deaths"]].sum()

plt.figure(figsize=(12, 6))
daily_summary.plot()
plt.title("COVID-19 Trend Over Time in India")
plt.xlabel("Date")
plt.ylabel("Number of Cases")
plt.grid(True)
plt.tight_layout()
plt.show()